version: '3.8'
services:
  front:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app  # Para desenvolvimento
    command: npm start