// app/layout.js
import ReactQueryProvider from '@/providers/reactQueryProvider';
import './globals.css'; 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" suppressHydrationWarning={true}>
       <ReactQueryProvider>
        <body className='bg-zinc-500'>
          {children}
        </body>
       </ReactQueryProvider>
    </html>
  );
}